minio:
  access-key: 7Kd6IvgtNCKz0lFS2kdQ
  secret-key: GxGK8eLRBPLULwAw7rlARGOfdJGhmdmWQb3vL5w2
  url: http://59.153.164.121:9000
  bucket-name: mywallpaper

spring:
  datasource:
    url: jdbc:mysql://59.153.164.121:3306/mywallpaper?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver