server:
  port: 8088
spring:
  profiles:
    active: dev
#    active: test
  application:
    name: MyWallpaper
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret-key: xiaoyangxiaoyangxiaoyangxiaoyangxiaoyangxiaoyang # 至少32位长度
  time-out: 168 # 以小时为单位